Add version to postgres image
Because at the time I wrote this commit, postgres:alpine is actually
version 14 of postgresSQL, which use SCRAM-SHA-256 as default of
password management and authentication system, and migrate v4.7.1
doesn't support that yet (actually lib/pq), so we will get this error while doing
migration.

error: pq: unknown authentication response: 10

Ref:
    - [PostgreSQL 14 Released! - Security Enhancements](https://www.postgresql.org/about/news/postgresql-14-released-2318/)